### ISSUE TITLE
Disable text select

### ISSUE THREAD

**Issue by mkermani144** [mkermani144/wanna#218]
Most of the texts are selectable in Wanna. This is ugly, as Wanna is an app, not a website.

**Comment by abiduzz420** [comment]
Hey @mkermani144 I would like to take up this issue. Please assign it to me. 

I am looking to create globalStyle.js where I define globalStyle constants and export them. where I find TextField i shall put this style variable. Please let me know if you are okay with it. Any other suggestions, happy to consider.

Cheers!
