### ISSUE TITLE
Linux Height of the window resize problem

### ISSUE THREAD

**Issue by davutkara** [mkermani144/wanna#229]
I am using linux mint 18.2 Sonya with mate desktop.
I can't change height of the window. 
Add button is below the panel.
![image](https://user-images.githubusercontent.com/10008440/30523591-9d2d7c74-9bec-11e7-88dc-444ffb73c55f.png)

**Comment by mkermani144** [comment]
@davutkara thanks for issue.
The minimum app size is set to `1024x768` by default. You are probably using the app in a monitor with this resolution or below, hence the problem you mentioned.
In the next versions of Wanna, we will add an option in the settings to set minimum app size.

**Comment by nkossy** [comment]
i am running *ubuntu 16.04* and am having the same height problems my screen resoultion is `1366x768(16:9)`

**Comment by mkermani144** [comment]
@nkossy 
You have the same problem. The minimum height of the app itself is 768px, but your screen height is 768px **including** your toolbar, etc. hence the problem.
This resolution minimum limit problem will be fixed in the next versions of Wanna.

**Comment by mkermani144** [comment]
@davutkara @nkossy 
If you can't wait and this resolution limit sucks, there is a workaround. You can easily edit the `main.js` file of the app and change the `minHeight` to your favor. For me, the path for this file is `/usr/lib/wanna/resources/app/main.js` on Ubuntu 17.04. Just open the file and change `minHeight: 768` to something suitable for you.

**Comment by nkossy** [comment]
# it now looks okay.
