### ISSUE TITLE
Keyboard shortcut: Add task/idea by pressing Enter

### ISSUE THREAD

**Issue by mkermani144** [mkermani144/wanna#243]
It's boring to click the button, especially when you want to add multiple tasks/ideas. Most users expect this keyboard shortcut to be available, as it is in many other applications.

**Comment by mvinoba** [comment]
Would pressing Enter open the Task or the Idea dialog? Or would it simply open the FAB? I'm willing to help this feature get added, I already coded this feature but it only opens/closes the FAB for now.

**Comment by mkermani144** [comment]
@mvinoba
It's not about opening the FAB, dialog or anything else, but it's about closing the opened dialog (and adding the idea/task) by pressing Enter. Opening task/idea dialog has been added to the app previously.

**Comment by mvinoba** [comment]
Sure, I thought of wrapping `<HotKeys>` in NewIdeaDialog's render's return while defining the approppriate handler and keyMap binding to `this.handleRequestAdd`. But that didn't work, probably something to do with the focus, perhaps this is beyond my React knowledge. I appreciate your answer anyways.
