### ISSUE TITLE
releases for macos?

### ISSUE THREAD

**Issue by Mr0Null** [mkermani144/wanna#257]
Hi there, great job!
I wanted to use this app on MacOS, but it seems it hasn't been built on mac yet, so is there any help I can suggest ...?

**Comment by mkermani144** [comment]
@Mr0Null 
My thanks.  
I will probably release a new patch soon, in which OSX version of the app will be added too. I keep this issue open, however, until this OSX version of the app is released.

**Comment by mkermani144** [comment]
Voila! The release for MacOS is available [here](https://github.com/mkermani144/wanna/releases/tag/1.0.0-alpha.2%2Bflex), so I will close this. Enjoy Wanna on Mac!
