### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by disorganised-mess** [mkermani144/wanna#275]
I'd like to see it not be required to designate a day and time when creating a task. Sometimes I don't need a deadline, I just want to be able to list something without the need to time-track and schedule.

**Comment by mkermani144** [comment]
@disorganised-mess 
Ideas are what you want. You can simply add an idea, as they don't need start and due dates.

**Comment by disorganised-mess** [comment]
OK, still learning, thanks.
